# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

xls_formats <- function(path) {
    .Call('exell_xls_formats', PACKAGE = 'exell', path)
}

xls_sheets <- function(path) {
    .Call('exell_xls_sheets', PACKAGE = 'exell', path)
}

xls_col_types <- function(path, na, i = 0L, nskip = 0L, n = 100L) {
    .Call('exell_xls_col_types', PACKAGE = 'exell', path, na, i, nskip, n)
}

xls_col_names <- function(path, i = 0L, nskip = 0L) {
    .Call('exell_xls_col_names', PACKAGE = 'exell', path, i, nskip)
}

xls_cols <- function(path, i, col_names, col_types, na, nskip = 0L) {
    .Call('exell_xls_cols', PACKAGE = 'exell', path, i, col_names, col_types, na, nskip)
}

xlsx_sheets_ <- function(xml) {
    .Call('exell_xlsx_sheets_', PACKAGE = 'exell', xml)
}

xlsx_strings_ <- function(xml) {
    .Call('exell_xlsx_strings_', PACKAGE = 'exell', xml)
}

