# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

xls_sheets <- function(path) {
    .Call(`_readxl_xls_sheets`, path)
}

xls_date_formats <- function(path) {
    .Call(`_readxl_xls_date_formats`, path)
}

read_xls_ <- function(path, sheet_i, limits, shim, col_names, col_types, na, trim_ws, guess_max = 1000L, progress = TRUE) {
    .Call(`_readxl_read_xls_`, path, sheet_i, limits, shim, col_names, col_types, na, trim_ws, guess_max, progress)
}

xlsx_sheets <- function(path) {
    .Call(`_readxl_xlsx_sheets`, path)
}

xlsx_strings <- function(path) {
    .Call(`_readxl_xlsx_strings`, path)
}

xlsx_date_formats <- function(path) {
    .Call(`_readxl_xlsx_date_formats`, path)
}

parse_ref <- function(ref) {
    .Call(`_readxl_parse_ref`, ref)
}

read_xlsx_ <- function(path, sheet_i, limits, shim, col_names, col_types, na, trim_ws, guess_max = 1000L, progress = TRUE) {
    .Call(`_readxl_read_xlsx_`, path, sheet_i, limits, shim, col_names, col_types, na, trim_ws, guess_max, progress)
}

zip_xml <- function(zip_path, file_path) {
    invisible(.Call(`_readxl_zip_xml`, zip_path, file_path))
}

