# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

xls_formats <- function(path) {
    .Call('readxl_xls_formats', PACKAGE = 'readxl', path)
}

xls_sheets <- function(path) {
    .Call('readxl_xls_sheets', PACKAGE = 'readxl', path)
}

xls_col_names <- function(path, i = 0L, nskip = 0L) {
    .Call('readxl_xls_col_names', PACKAGE = 'readxl', path, i, nskip)
}

xls_col_types <- function(path, na, sheet = 0L, nskip = 0L, guess_max = 1000L, has_col_names = FALSE) {
    .Call('readxl_xls_col_types', PACKAGE = 'readxl', path, na, sheet, nskip, guess_max, has_col_names)
}

xls_cols <- function(path, i, col_names, col_types, na, nskip = 0L) {
    .Call('readxl_xls_cols', PACKAGE = 'readxl', path, i, col_names, col_types, na, nskip)
}

read_xls_ <- function(path, sheet_i, col_names, col_types, na, nskip = 0L, guess_max = 1000L) {
    .Call('readxl_read_xls_', PACKAGE = 'readxl', path, sheet_i, col_names, col_types, na, nskip, guess_max)
}

xlsx_sheets <- function(path) {
    .Call('readxl_xlsx_sheets', PACKAGE = 'readxl', path)
}

xlsx_strings <- function(path) {
    .Call('readxl_xlsx_strings', PACKAGE = 'readxl', path)
}

xlsx_date_styles <- function(path) {
    .Call('readxl_xlsx_date_styles', PACKAGE = 'readxl', path)
}

xlsx_dim <- function(path, sheet = 0L, nskip = 0L) {
    .Call('readxl_xlsx_dim', PACKAGE = 'readxl', path, sheet, nskip)
}

parse_ref <- function(ref) {
    .Call('readxl_parse_ref', PACKAGE = 'readxl', ref)
}

xlsx_col_types <- function(path, sheet = 0L, na = character(), nskip = 0L, guess_max = 1000L, sheetHasColumnNames = FALSE) {
    .Call('readxl_xlsx_col_types', PACKAGE = 'readxl', path, sheet, na, nskip, guess_max, sheetHasColumnNames)
}

xlsx_col_names <- function(path, i = 0L, nskip = 0L) {
    .Call('readxl_xlsx_col_names', PACKAGE = 'readxl', path, i, nskip)
}

read_xlsx_ <- function(path, sheet, col_names, col_types, na, nskip = 0L, guess_max = 1000L) {
    .Call('readxl_read_xlsx_', PACKAGE = 'readxl', path, sheet, col_names, col_types, na, nskip, guess_max)
}

zip_xml <- function(zip_path, file_path) {
    invisible(.Call('readxl_zip_xml', PACKAGE = 'readxl', zip_path, file_path))
}

